fixing PixiJS Deprecation Warnings
pixijs/filters pull request #389
Opened 2023-05-20 01:27 UTC by FloodGames

2023-05-20 15:23 UTC, ijontan approved these changes
seems to be correct, someone please approve this

2023-05-20 15:39 UTC, FloodGames commented
Thanks.

I'm on my way, it isn't finished, feel free to continue on this one. 

`git clone https://github.com/FloodGames/filters.git`

![image](https://github.com/pixijs/filters/assets/60991890/4c08a9b9-1574-4341-b94e-da69f61d0b54)

Note, sometimes Color is already a type!

2023-05-20 16:08 UTC, FloodGames commented
Please check the code before approving!

![image](https://github.com/pixijs/filters/assets/60991890/6b1a69be-c58e-41a8-b976-4179cf13596d)

The if/else seem a bit unnecessary?

2023-05-20 16:16 UTC, FloodGames commented
Also fix this please:
![image](https://github.com/pixijs/filters/assets/60991890/ee29b5e3-f5a4-40ce-9b92-bc02ad39ac23)

2023-07-08 00:39 UTC, bigtimebuddy requested changes
Thanks so much for your help. You really took a big swing with this PR. My general feedback is that this PR is _way_ too big. We don't like omnibus pull-requests, they are hard to review and easy to miss mistakes (therefore prone to regressions, bugs, etc).

Seems like you're doing a bunch of things here:

* Updating dependencies
* Fixing deprecations warnings

These should be different PRs. And because the Color stuff is so vast, it would be better to do the color stuff separate from the other deprecation warnings like `settings` properties being moved.

2023-07-08 00:44 UTC, bigtimebuddy requested changes

2023-07-08 00:44 UTC, bigtimebuddy commented on filters/advanced-bloom/src/AdvancedBloomFilter.ts
> +    protected _resolution: number = window.devicePixelRatio;
This should be `Filter.defaultResolution` not `devicePixelRatio`.

2023-07-08 00:44 UTC, bigtimebuddy commented on filters/bevel/src/BevelFilter.ts
> +        return new Color(this.uniforms.lightColor).toNumber();
Many places you're using `new Color()`, for simple conversions, consider using `Color.shared.setValue()` instance instead as this does not generate extra garbage.

2023-07-08 00:44 UTC, bigtimebuddy commented on filters/bloom/src/BloomFilter.ts
> +    constructor(blur: BlurValue = 2, quality = 4, resolution: number = window.devicePixelRatio, kernelSize = 5)
Again this should be `Filter.defaultResolution`

2023-07-08 00:44 UTC, bigtimebuddy commented on filters/color-overlay/src/ColorOverlayFilter.ts
> +    constructor(color: ColorType = 0x000000, alpha = 1)
`@pixi/core` has a type called `ColorSource` which should be used here instead of `ColorType`

2023-07-08 00:44 UTC, bigtimebuddy commented on filters/color-replace/src/ColorReplaceFilter.ts
> +    constructor(originalColor: ColorType = 0xFF0000, newColor: ColorType = 0x000000, epsilon = 0.4)
Again, use the `ColorSource` type instead.

2024-01-05 07:17 UTC, magos1983 requested changes

2024-01-05 07:17 UTC, magos1983 commented on filters/color-gradient/src/utils.ts
> +            return [new Color(value).toNumber()];
this should be `return Color.shared.setValue(value).toRgbArray();`

2024-01-05 07:17 UTC, magos1983 commented on filters/color-overlay/src/ColorOverlayFilter.ts
> +            this._color = new Color(value).toNumber();
shouldn't this be 
```
Color.shared.setValue(value).toRgbArray(arr);
this._color = value;
```

2024-01-05 07:17 UTC, magos1983 commented on filters/color-overlay/src/ColorOverlayFilter.ts
> +            this._color = new Color(arr).toNumber();
and here it should be:
`this._color = Color.shared.setValue(arr).toNumber();`

2024-01-05 07:17 UTC, magos1983 commented on filters/glow/src/GlowFilter.ts
> +        return new Color(this.uniforms.glowColor).toNumber();
`return Color.shared.setValue(this.uniforms.glowColor).toNumber()`

2024-01-05 07:17 UTC, magos1983 commented on filters/glow/src/GlowFilter.ts
> +        this.uniforms.glowColor = new Color(value);
Color.shared.setValue(value).toRgbArray(this.uniforms.glowColor);

2024-03-07 00:45 UTC, bigtimebuddy commented
Thank you for creating this PR and contributing, but unfortunately this PR has gotten a little stale. I'm going to close it, but if you want to continue to work on it, I would suggest that we break this down into smaller pull-requests to make it a little more manageable.

2024-03-07 00:45 UTC, closed without merging